name: "MyAnimeList"
guid: "41b9d545-325d-4f3e-b712-085b3b7f1b0c"
version: "0.0.0.1"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "MyAnimeList metadata provider"
description: >
  MyAnimeList metadata provider

category: "Metadata"
owner: "Fribbtastic"
artifacts:
- "Jellyfin.Plugin.MyAnimeList.dll"
changelog: >
  changelog